apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
  namespace: {{ .Values.global.spire.namespace }}
data:
  registrar.conf: |-
    log_level = "debug"
    log_path = "/dev/stdout"
    addr = "0.0.0.0:443"
    cluster = "quickstart"
    server_socket_path = "/run/spire/socket/registration.sock"
    trust_domain = "quickstart.greymatter.io"
    cert_path = "/run/spire/tls/registrar.spire.svc.crt"
    key_path = "/run/spire/tls/registrar.spire.svc.key"
    cacert_path = "/run/spire/tls/ca.crt"
    insecure_skip_client_verification	= true
    pod_label = "gmproxy"
  server.conf: |-
    server {
      bind_address = "0.0.0.0"
      bind_port = "8443"
      registration_uds_path = "/run/spire/socket/registration.sock"
      trust_domain = "quickstart.greymatter.io"
      data_dir = "/run/spire/data"
      log_level = "debug"
      upstream_bundle = true
      default_svid_ttl = "1h"
      ca_subject = {
        country = ["US"],
        organization = ["Grey Matter"],
        common_name = "Quickstart",
      }
    }

    plugins {
      DataStore "sql" {
        plugin_data {
          database_type = "sqlite3"
          connection_string = "/run/spire/data/datastore.sqlite3"
        }
      }

      NodeAttestor "k8s_sat" {
        plugin_data {
          clusters = {
            "quickstart" = {
              service_account_whitelist = ["spire:agent"]
              use_token_review_api_validation = true
            }
          }
        }
      }

      NodeResolver "noop" {
        plugin_data {}
      }

      KeyManager "disk" {
        plugin_data {
          keys_path = "/run/spire/data/keys.json"
        }
      }

      Notifier "k8sbundle" {
        plugin_data {
          config_map = "server-bundle"
        }
      }

      UpstreamCA "disk" {
        plugin_data {
          cert_file_path = "/run/spire/ca/intermediate.crt"
          key_file_path = "/run/spire/ca/intermediate.key"
          bundle_file_path = "/run/spire/ca/root.crt"
        }
      }
    }
