# xDs values
global:
  environment: kubernetes
  domain:
  route_url_name:
  remove_namespace_from_url: ''
  exhibitor:
    replicas: 1
  # Might want to point the xds values to the global values or vice versa
  xds:
    port:
    cluster:

xds:
  image: 'docker.production.deciphernow.com/deciphernow/gm-xds:0.2.6'
  imagePullPolicy: Always
  version: 0.2.6
  cluster: greymatter
  #host: 'xds.greymatter.svc.cluster.local'
  port: 18000
  use_zk: 'true'
  logging_level: info
  zk_base_path: '/services'
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

sidecar:
  version: 0.7.1
  image: 'docker.production.deciphernow.com/deciphernow/gm-proxy:0.7.1'
  imagePullPolicy: Always
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  envvars:
    metrics_port:
      type: value
      value: '8080'
    port:
      type: value
      value: '8443'
    kafka_topic:
      type: value
      value: 'xds'
    proxy_dynamic:
      type: value
      value: 'false'
    service_port:
      type: value
      value: '{{ .Values.xds.port }}'
  # Setcreate_sidecar_secret to true if you are attempting to deploy Catalog by itself.
  # Ideally, catalog is deployed as a dependency to Grey Matter, which creates the
  # sidecar secret, but if individual testing is being done, the sidecar secret will
  # need to be created.
  create_sidecar_secret: false
  certificates:
    # name: sidecar
    # ca: |-
    #   -----BEGIN CERTIFICATE-----
    #   ...
    #   -----END CERTIFICATE-----
    # cert: |-
    #   -----BEGIN CERTIFICATE-----
    #   ...
    #   -----END CERTIFICATE-----
    # key: |-
    #   -----BEGIN RSA PRIVATE KEY-----
    #   ...
    #   -----END RSA PRIVATE KEY-----
