apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.spire.server.name }}
  namespace: {{ .Release.Namespace }}
data:
  server.conf: |-
    server {
      bind_address = "0.0.0.0"
      bind_port = "8081"
      trust_domain = "{{ .Values.global.spire.trustDomain }}"
      data_dir = "/run/spire/data"
      log_level = "DEBUG"
      svid_ttl = "1h"
      registration_uds_path = "{{.Values.spire.server.registrationAPIPath}}"
      upstream_bundle = true
      ca_subject = {
        Country = ["US"],
        Organization = ["SPIFFE"],
        CommonName = "Grey Matter SPIFFE CA",
      }
    }

    plugins {
      DataStore "sql" {
        plugin_data {
          database_type = "sqlite3"
          connection_string = "/run/spire/data/datastore.sqlite3"
        }
      }

      NodeAttestor "k8s_sat" {
        plugin_data {
          clusters = {
            # NOTE: Change this to your cluster name
            "{{ .Values.spire.clusterName }}" = {
              service_account_whitelist = ["{{ .Release.Namespace }}:spire-agent"]
              use_token_review_api_validation = true
            }
          }
        }
      }

      NodeResolver "noop" {
        plugin_data {}
      }

      KeyManager "disk" {
        plugin_data {
          keys_path = "/run/spire/data/keys.json"
        }
      }

      UpstreamCA "disk" {
        plugin_data {
          ttl = "12h"
          key_file_path = "/run/spire/secrets/bootstrap.key"
          cert_file_path = "/run/spire/config/bootstrap.crt"
        }
      }
    }

  bootstrap.crt: |-
{{ .Values.spire.certs.bootstrap.crt | indent 4 }}
