global:
  environment: kubernetes
  domain:
  route_url_name:
  remove_namespace_from_url: false
  catalog:
    version: 0.3.6
  dashboard:
    version: 2.5.0
  data:
    version: 0.2.3
  documentation:
    version: 3.0.0
  edge:
    version: 0.7.1
  exhibitor:
    replicas: 1
    version:
  jwt:
    version: 0.2.0
  slo:
    version: 0.4.0
  xds:
    cluster: greymatter
    port: 18000
    version: 0.2.6

catalog:
  image: docker.production.deciphernow.com/deciphernow/gm-catalog:{{ $.Values.global.catalog.version }}
  source: control
  debug: 'true'
  imagePullPolicy: Always
  resources:
    limits:
      cpu: 200m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi

  port: 9080

  services:
    service_0:
      
      cluster_name: catalog
      enable_instance_metrics: "true"
      
      capability: 'Grey Matter'
      documentation: '/services/catalog/latest/'
      name: 'Grey Matter Catalog'
      owner: 'Decipher'
      version: '{{ $.Values.global.catalog.version | trunc 3 }}'

    service_1:
      # 
      # cluster_name: control
      # enable_instance_metrics: "true"
      # 
      capability: 'Grey Matter'
      documentation: ''
      name: 'Grey Matter Control'
      owner: 'Decipher'
      version: '{{ $.Values.global.xds.version | trunc 3 }}'
      

    service_2:
      
      cluster_name: dashboard
      enable_instance_metrics: "true"
      
      capability: 'Grey Matter'
      documentation: ''
      name: 'Grey Matter Dashboard'
      owner: 'Decipher'
      version: '{{ $.Values.global.dashboard.version | trunc 3 }}'
      

    service_3:
      
      cluster_name: data
      enable_instance_metrics: "true"
      
      capability: 'Grey Matter'
      documentation: '/services/data/latest/static/ui/index.html'
      name: 'Grey Matter Data'
      owner: 'Decipher'
      version: '{{ $.Values.global.data.version | trunc 3 }}'
      

    service_4:
      
      cluster_name: jwt-security
      enable_instance_metrics: "true"
      
      capability: 'Grey Matter'
      documentation: ''
      name: 'Grey Matter JWT Security'
      owner: 'Decipher'
      version: '{{ $.Values.global.jwt.version | trunc 3 }}'
      

    service_5:
      
      cluster_name: edge
      enable_instance_metrics: "true"
      
      capability: 'Grey Matter'
      documentation: ''
      name: 'Grey Matter Edge'
      owner: 'Decipher'
      version: '{{ $.Values.global.edge.version | trunc 3 }}'
      

    service_6:
      
      cluster_name: slo
      enable_instance_metrics: "true"
      
      capability: 'Grey Matter'
      documentation: ''
      name: 'Grey Matter Service Level Objectives'
      owner: 'Decipher'
      version: '{{ $.Values.global.slo.version | trunc 3 }}'
      

    service_7:
      
      cluster_name: documentation
      enable_instance_metrics: "true"
      
      capability: 'Grey Matter'
      documentation: '/services/documentation/latest/'
      name: 'Grey Matter Documentation'
      owner: 'Decipher'
      version: '{{ $.Values.global.documentation.version | trunc 3 }}'
      

sidecar:
  version: '{{- $.Values.global.catalog.sidecar.version | default "0.8.0" }}'
  image: 'docker.production.deciphernow.com/deciphernow/gm-proxy:{{ tpl $.Values.sidecar.version $ }}'
  imagePullPolicy: Always
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  envvars:
    xds_cluster:
      type: value
      value: 'catalog'
    kafka_topic:
      type: value
      value: 'gm-catalog'

  # Set this to true if you are attempting to deploy Catalog by itself.
  # Ideally, catalog is deployed as a dependency to Grey Matter, which creates the
  # sidecar secret, but if individual testing is being done, the sidecar secret will
  # need to be created.
  create_sidecar_secret: false
  certificates:
    name: sidecar
    ca: |-
      -----BEGIN CERTIFICATE-----
      ...
      -----END CERTIFICATE-----
    cert: |-
      -----BEGIN CERTIFICATE-----
      ...
      -----END CERTIFICATE-----
    key: |-
      -----BEGIN RSA PRIVATE KEY-----
      ...
      -----END RSA PRIVATE KEY-----
