{{- if and .Values.global.environment (eq .Values.global.environment "openshift") }}

kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: edge
  namespace: {{ .Release.Namespace }}
spec:
  host: {{ include "greymatter.domain" . }}
  port: 
    targetPort: proxy
  tls:
    termination: passthrough
  to:
    kind: Service
    name: edge
    weight: 100
  wildcardPolicy: None

{{- else }}

apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: edge
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - tcp:
      port: '80'
      backend:
        serviceName: edge
        servicePort: 8080
  - tcp:
      port: '443'
      backend:
        serviceName: edge
        servicePort: 8080
{{- end }}