{{- if and .Values.environment (eq .Values.environment "openshift") }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: edge
  namespace: {{ .Release.Namespace }}
spec:
  host: {{ .Values.route_url_name }}.{{ .Release.Namespace }}.{{ .Values.domain}}
  port: 
    targetPort: http
  tls:
    termination: passthrough
  to:
    kind: Service
    name: edge
    weight: 100
  wildcardPolicy: None
{{- else }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  name: edge
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - host: {{ .Values.route_url_name }}.{{ .Release.Namespace }}.{{ .Values.domain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: edge
              servicePort: 8443
{{- end }}