global:
  environment: kubernetes
  domain: 
  route_url_name: 
  remove_namespace_from_url: ''
  exhibitor:
    replicas: 1
  xds:
    port: 18000
    cluster: greymatter

slo:
  version: 0.4.0
  image: docker.production.deciphernow.com/deciphernow/gm-slo:0.4.0
  imagePullPolicy: Always
  resources:
    limits:
      cpu: 250m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

sidecar:
  version: 0.7.1
  image: 'docker.production.deciphernow.com/deciphernow/gm-proxy:0.7.1'
  metrics_key_function: depth
  imagePullPolicy: Always
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  envvars:
  - type: value
    nane: ingress_use_tls
    value: 'true'
  - type: value
    nane: ingress_ca_cert_path
    value: "/etc/proxy/tls/sidecar/ca.crt"
  - type: value
    nane: ingress_cert_path
    value: "/etc/proxy/tls/sidecar/server.crt"
  - type: value
    nane: ingress_key_path
    value: "/etc/proxy/tls/sidecar/server.key"
  - type: value
    nane: metrics_port
    value: '8081'
  - type: value
    nane: port
    value: '8080'
  - type: value
    nane: proxy_dynamic
    value: 'true'
  - type: value
    nane: service_host
    value: '127.0.0.1'
  - type: value
    nane: service_port
    value: '1337'
  - type: value
    name: kafka_zk_discover
    value: 'false'
  - type: value
    name: kafka_server_connection
    value: 'kafka:9091,kafka2:9091'
  - type: value
    name: kafka_enabled
    value: 'false'
  - type: value
    name: kafka_topic
    value: 'gm-slo'
  - type: value
    name: metrics_key_function
    value: 'depth'
  - type: value
    name: obs_enabled
    value: 'false'
  - type: value
    name: obs_enforce
    value: 'false'
  - type: value
    name: obs_full_response
    value: 'false'
    
  # Set this to true if you are attempting to deploy SLO by itself.
  # Ideally, catalog is deployed as a dependency to Grey Matter, which creates the
  # sidecar secret, but if individual testing is being done, the sidecar secret will
  # need to be created.
  create_sidecar_secret: false
  certificates:
    # name: sidecar
    # ca: |-
    #   -----BEGIN CERTIFICATE-----
    #   ...
    #   -----END CERTIFICATE-----
    # cert: |-
    #   -----BEGIN CERTIFICATE-----
    #   ...
    #   -----END CERTIFICATE-----
    # key: |-
    #   -----BEGIN RSA PRIVATE KEY-----
    #   ...
    #   -----END RSA PRIVATE KEY-----

postgres:
  data_mount_point: /var/lib/pgsql/data
  openshift:
    image: 'docker.io/centos/postgresql-95-centos7:9.5'
  k8s:
    image: 'postgres:9.5'
  imagePullPolicy: Always
  replica_count: 1
  #private_image: false
  resources:
    limits:
     cpu: 200m
     memory: 512Mi
    requests:
     cpu: 100m
     memory: 128Mi


  credentials:
    secret_name: postgres-credentials
    username: greymatter
    password: greymatter
    database: greymatter

  ssl:
    enabled: false
    name: postgres-ssl-certs
    mount_path: /secret/cert
    certificates:
  #  - name: mongo-ssl-certs
  #    ca: |-
  #      -----BEGIN CERTIFICATE-----
  #      ...
  #      -----END CERTIFICATE-----
  #    cert: |-
  #      -----BEGIN CERTIFICATE-----
  #      ...
  #      -----END CERTIFICATE-----
  #    key: |-
  #      -----BEGIN RSA PRIVATE KEY-----
  #      ...
  #      -----END RSA PRIVATE KEY-----

  envvars:
    # Any environments listed here will be populated in the postgres yaml. Use the
    # correct variables for the version of Postgres you are deploying
    #
    # Formerly, when .Values.global.environment was set to "openshift", these environment variables were used:
    #   - POSTGRESQL_USER
    #   - POSTGRESQL_PASSWORD
    #   - POSTGRESQL_DATABASE
    # When .Values.global.environment was set to "kubernetes", these were used:
    #   - POSTGRES_USER
    #   - POSTGRES_PASSWORD
    #   - POSTGRES_DB
    - type: secret
      name: POSTGRESQL_USER
      secret: postgres-credentials
      key: username
    - type: secret
      name: POSTGRESQL_PASSWORD
      secret: postgres-credentials
      key: password
    - type: secret
      name: POSTGRESQL_DATABASE
      secret: postgres-credentials
      key: database
