global:
  environment: kubernetes
  domain:
  route_url_name:
  remove_namespace_from_url: false
  zone: default-zone
  catalog:
    version: 0.3.6
    sidecar:
      version: # 0.7.1
  dashboard:
    version: 2.5.0
    sidecar:
      version:
    prometheus_sidecar:
      version: 0.8.0
  data:
    version: 0.2.3
    sidecar:
      version:
  documentation:
    version: 3.0.0
    sidecar:
      version:
  edge:
    version: 0.7.1
    sidecar:
      version:
  exhibitor:
    replicas: 1
    version: 
    sidecar:
      version:
  jwt:
    version: 0.2.0
    sidecar:
      version:
  slo:
    version: 0.4.0
    sidecar:
      version:
  xds:
    cluster: greymatter
    port: 18000
    version: 0.2.6
    sidecar:
      version:

sidecar:
  # Set this to true if you are attempting to deploy Catalog by itself.
  # Ideally, catalog is deployed as a dependency to Grey Matter, which creates the
  # sidecar secret, but if individual testing is being done, the sidecar secret will
  # need to be created.
  create_sidecar_secret: true
  certificates:
    name: sidecar
    ca: |-
      -----BEGIN CERTIFICATE-----
      ...
      -----END CERTIFICATE-----
    cert: |-
      -----BEGIN CERTIFICATE-----
      ...
      -----END CERTIFICATE-----
    key: |-
      -----BEGIN RSA PRIVATE KEY-----
      ...
      -----END RSA PRIVATE KEY-----
