apiVersion: v2
appVersion: 1.2
description: A Helm chart to deploy Spire
name: spire
version: 2.2.1
icon: https://s3.amazonaws.com/decipher-public/grey-matter/branding/grey-matter-mark-rgb.png
maintainers:
  - name: greymatter-io
    email: engineering@greymatter.io
keywords:
  - Grey Matter
  - service mesh
  - spire
  - spiffe
dependencies:
  - name: agent
    repository: file://./agent
    version: '2.2.2'

  - name: server
    repository: file://./server
    version: '2.2.2'
