global:
  environment: kubernetes
  domain:
  route_url_name:
  remove_namespace_from_url: ''
  exhibitor:
    replicas: 1
  xds:
    port: 18000
    cluster: greymatter

documentation:
  name: documentation
  base_path: '/services/documentation/3.0.0/'
  version: 3.0.0
  image: 'docker.production.deciphernow.com/deciphernow/gm-documentation:v3.0.0'
  imagePullPolicy: Always
  envvars:
    - type: value
      name: base_path
      value: '/services/documentation/3.0.0/'
    - type: value
      name: hidden_content_titles
      value: 'Setup,FAQ'

sidecar:
  version: 0.7.1
  image: 'docker.production.deciphernow.com/deciphernow/gm-proxy:0.7.1'
  imagePullPolicy: Always
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  envvars:
    - type: value
      name: ingres_use_tls
      value: 'true'
    - type: value
      name: ingress_ca_cert_path
      value: '/etc/proxy/tls/sidecar/ca.crt'
    - type: value
      name: ingress_cert_path
      value: '/etc/proxy/tls/sidecar/server.crt'
    - type: value
      name: ingress_key_path
      value: '/etc/proxy/tls/sidecar/server.key'
    - type: value
      name: metrics_key_function
      value: 'depth'
    - type: value
      name: metrics_port
      value: '8081'
    - type: value
      name: port
      value: '9080'
    - type: value
      name: proxy_dynamic
      value: 'true'
    - type: value
      name: service_port
      value: '8080'
    - type: value
      name: service_host
      value: '127.0.0.1'
    - type: value
      name: obs_enabled
      value: 'false'
    - type: value
      name: kafka_zk_discover
      value: 'false'
    - type: value
      name: kafka_server_connection
      value: 'kafka:9091,kafka2:9091'
    - type: value
      name: obs_full_response
      value: 'false'
    - type: value
      name: kafka_enabled
      value: 'false'
    - type: value
      name: kafka_topic
      value: 'gm-documentation'
    - type: value
      name: obs_enforce
      value: 'false'

  # Set this to true if you are attempting to deploy Catalog by itself.
  # Ideally, catalog is deployed as a dependency to Grey Matter, which creates the
  # sidecar secret, but if individual testing is being done, the sidecar secret will
  # need to be created.
  create_sidecar_secret: false
  certificates:
    name: sidecar
    ca: |-
      -----BEGIN CERTIFICATE-----
      ...
      -----END CERTIFICATE-----
    cert: |-
      -----BEGIN CERTIFICATE-----
      ...
      -----END CERTIFICATE-----
    key: |-
      -----BEGIN RSA PRIVATE KEY-----
      ...
      -----END RSA PRIVATE KEY-----
